# Generated by Django 4.1.5 on 2023-01-27 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0012_alter_defaultvalue_defaultvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserves.staff', verbose_name='スタッフ'),
        ),
    ]
