# Generated by Django 4.1.5 on 2023-01-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0014_remove_booking_first_name_remove_booking_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=True, verbose_name='取消情報'),
        ),
    ]
